fix: pass inputs as envs
Signed-off-by: Prashant Shahi <me@prashantshahi.dev>

diff --git a/.github/workflows/repository-dispatch.yaml b/.github/workflows/repository-dispatch.yaml
--- a/.github/workflows/repository-dispatch.yaml
+++ b/.github/workflows/repository-dispatch.yaml
@@ -21,19 +21,23 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: trigger-event
+        env:
+          target_repository: ${{ inputs.target_repository }}
+          event_type: ${{ inputs.event_type }}
+          payload: ${{ inputs.payload }}
         run: |
           echo "workflow_dispatch triggered by ${{ github.actor }}"
           echo "validating payload JSON"
-          if ! echo ${{ inputs.payload }} | jq '.' > /dev/null; then
-            echo "invalid JSON payload ${{ inputs.payload }}"
+          if ! echo ${payload} | jq '.' > /dev/null; then
+            echo "invalid JSON payload ${payload}"
             exit 1
           fi
 
           echo "creating cURL payload"
-          if [[ "${{ inputs.payload }}" != "{}" ]]; then
-            curl_payload="{\"event_type\":\"${{ inputs.event_type }}\",\"client_payload\":${{ inputs.payload }}}"
+          if [[ "${payload}" != "{}" ]]; then
+            curl_payload="{\"event_type\":\"${event_type}\",\"client_payload\":${payload}}"
           else
-            curl_payload="{\"event_type\":\"${{ inputs.event_type }}\"}"
+            curl_payload="{\"event_type\":\"${event_type}\"}"
           fi
 
           echo "payload: ${curl_payload}"
@@ -41,7 +45,7 @@ jobs:
           if ! curl -sSfL -X POST -H "Content-Type: application/json" \
             -H "Authorization: Bearer ${{ secrets.REPOSITORY_TOKEN }}" \
             -d "${curl_payload}" \
-            "https://api.github.com/repos/${{ github.repository_owner }}/${{ inputs.target_repository }}/dispatches" > /dev/null 2>&1; then
+            "https://api.github.com/repos/${{ github.repository_owner }}/${target_repository}/dispatches" > /dev/null 2>&1; then
             echo "failed to dispatch event"
             exit 1
           fi
