chore: add error-job dependency
Signed-off-by: Prashant Shahi <me@prashantshahi.dev>

diff --git a/.github/workflows/repository-dispatch-target.yaml b/.github/workflows/repository-dispatch-target.yaml
--- a/.github/workflows/repository-dispatch-target.yaml
+++ b/.github/workflows/repository-dispatch-target.yaml
@@ -5,7 +5,16 @@ on:
     types: [example-dispatch-event]
 
 jobs:
+  error-job:
+    runs-on: ubuntu-latest
+    steps:
+      - name: error
+        run: |
+          echo "This is an example error"
+          exit 1
   example-job:
+    if: ${{ always() && github.event.name == 'repository_dispatch' }}
+    needs: [error-job]
     runs-on: ubuntu-latest
     steps:
       - name: log-event
